### ISSUE TITLE
Require Error

### ISSUE THREAD

**Issue by DandroidDeveloper** [dferber90/horizon-react-native#2]
Error requiring unknown module '@horizon/client'

Any known fixes for this require error? I am in android studio on Ubuntu.

**Comment by dferber90** [comment]
Did you run "npm install"? This project is just a really tiny example, there's nearly no value in starting based on it. It's just an example of how to set things up, although they don't fully work afaik (as stated in the README).

**Comment by DandroidDeveloper** [comment]
ooooo, no I did not, I initialized my own horizon app, I will try cloning and using yours

**Comment by DandroidDeveloper** [comment]
I missed rm -r dist src, trying that now

**Comment by DandroidDeveloper** [comment]
Yeah, still the same error. I tried running npm install, and npm install horizon locally, the only difference I can see is that my package.json does not include the dependency for client... I thought that would be resolved with npm install. Tried it manually as well and still same error

**Comment by dferber90** [comment]
You need to run `npm install @horizon/client` in your project.

Closing this as it's not an issue with this project. Maybe read up on npm a bit :) The `@horizon` part is because `@horizon/client` is a [scoped package](https://docs.npmjs.com/misc/scope).

**Comment by DandroidDeveloper** [comment]
hahaha, well I made it to the error I am supposed to be having, thanks for your help though! 

Now this is my problem, doesn't seem like there is a fix... https://github.com/rethinkdb/horizon/issues/477
